title: "کاشان کامپوس"
description: "جامعه متخصصین و برنامه نویسان شهر کاشان"
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jemoji

collections:
  networks:
    output: true
    sidebar_label: Networks

jekyll_admin:
  hidden_links:
    - staticfiles
    - datafiles
    - configuration
  homepage: "posts"

exclude:
  - .all-contributorsrc
  - .editorconfig
  - .github
  - .gitignore
  - .jekyll-cache
  - .pre-commit-config.yaml
  - CODEOWNERS
  - codespell.txt
  - Gemfile
  - Gemfile.lock
  - vendor
  - server
  - super-linter.report
